/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    private String text;

    public App() {
        this.text = "Hello, world";
    }

    public App(String text) {
        this.text = text;
    }

    public String getGreeting() {
        return this.text;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
