/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.util.Date;

import static org.hamcrest.Matchers.is;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();

        Date date = new Date();

        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
        String actual = classUnderTest.getGreeting();
        assertEquals("Hello, world", actual);
    }

    @Test public void hamcrestを使ってみよう() {
        App app = new App();
        assertThat("Hello, world.", is(app.getGreeting()));
    }

    @Test public void コンストラクタに挨拶を渡せるようにする() {
        App app = new App("こんにちは！");

        assertEquals("こんにちは！", app.getGreeting());
    }
}
